---
title: "Factor Analysis"
author: "Riccardo Volpato"
format:
  html:
    embed-resources: true
    toc: true
editor: visual
bibliography: references.bib
execute:
  message: false
  warning: false
---

# Data Processing

```{r}
library(tidyverse)
library(gtools)
library(psych)
library(faux)
library(knitr)

set.seed(8675309) # makes sure random numbers are reproducible
```

```{r}
# read Qualtrics data without metadata rows
file_path <- "data/pilot/TPSai_13+March+2026_10.16.csv"
raw_data <- read_csv(file_path, n_max = 2)
colnames <- names(raw_data)

# Row 2 of the file is the question text row (index 1 after skip)
question_labels <- setNames(
  sub(".* - ", "", as.character(raw_data[1, ])),
  colnames
)
raw_data <- read_csv(file_path, col_names = colnames, skip = 3)
```

```{r}
# define variables for questions and answers
cols_trust    <- paste0("TR_", 1:23)
cols_distrust <- paste0("DT_", 1:13)
cols_company  <- paste0("CD_", 1:7)
cols_tpsai <- c(cols_trust, cols_distrust, cols_company)

likert_levels <- c(
  "Strongly disagree" = 1,
  "Disagree" = 2,
  "Neither agree nor disagree" = 3,
  "Agree" = 4,
  "Strongly agree" = 5,
  "Don't know" = NA
)

qid_label_map <- question_labels[cols_tpsai]
qid_label_df <- tibble(id = names(qid_label_map), text = qid_label_map)
```

```{r}
factors_data <- raw_data %>%
  select(all_of(cols_tpsai))  %>%
  mutate(across(all_of(cols_tpsai), ~ likert_levels[.x]))
```

# Correlations

## Correlation Matrix

```{r}
cor_matrix <- cor(factors_data, use = "pairwise.complete.obs")
```

```{r}
cor.plot(cor_matrix, numbers = FALSE, cex = 0.5)
```

```{r}
kable(round(cor_matrix, 2))
```

```{r}
write.csv(round(cor_matrix, 2), "data/pilot/sample_correlation_matrix.csv")
```

## Sub-scales correlation

```{r}
subscales <- factors_data %>%
  mutate(
    Trust    = rowMeans(pick(all_of(cols_trust)),    na.rm = TRUE),
    Distrust = rowMeans(pick(all_of(cols_distrust)), na.rm = TRUE),
    "Corporate Distrust"  = rowMeans(pick(all_of(cols_company)),  na.rm = TRUE)
  ) %>%
  select(Trust, Distrust, "Corporate Distrust")


cor_subscales <- cor(subscales, use = "pairwise.complete.obs")

cor_subscales %>% 
  as.data.frame() %>% 
  rownames_to_column("S1") %>% 
  pivot_longer(-S1, names_to = "S2", values_to = "r") %>% 
  filter(S1 < S2) %>% 
  kable(digits = 2)
```
